# Docker
# Build a Docker image and Push to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Web01/Dockerfile'        
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhubconnection'
        repository: 'gbbuenaflor'
        command: 'push'
        Dockerfile: '$(Build.SourcesDirectory)/Web01/Dockerfile'
        tags: '$(tag)'

 