apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  labels:
    app: mvc
data:
  db-connection-string: Server=mssql-service;Database=Web01DB;User=SA;Password=VM12345!@#12345;
