apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: ConfigMap
metadata:
  name: mssql-connection-configmap
  labels:
    app: mvc
data:
  db-connection-string: Server=mssql-service;Database=Web01DB;User=SA;Password=VM12345!@#12345;
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
  annotations: 
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Service
metadata:
  name: mssql-service-ext
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433 
  type: LoadBalancer
---
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: microsoft/mssql-server-linux
        resources:
           limits:
             cpu: "2"
             memory: "2Gi"
           requests:
             cpu: "0.5"
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "VM12345!@#12345"
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30200
  type: NodePort
---
kind: Service
metadata:
  name: mssql-service-ext
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433 
  type: LoadBalancer
--- 
kind: Deployment
metadata:
  name: aks01-web
  namespace: aks01-web
  labels:
    app: aks01-web
spec:
  selector:
    matchLabels:
      app: aks01-web
  replicas: 1 # run in 2 Pods
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aks01-web        
    spec:
      containers:
      - name: mvc
        image: gbbuenaflor/web01aspnetcore-app:v1 # #{ImageTag}# #v10 #v2.#{Build.BuildId}#
        imagePullPolicy: IfNotPresent
        ports:
        - name: container-port
        - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: container-port
          failureThreshold: 15
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: container-port
          failureThreshold: 15
          periodSeconds: 10
          initialDelaySeconds: 60
        env:
          - name: ConnectionStrings__WebDataContext
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: db-connection-string-secret
#              configMapKeyRef:
#                name: mssql-connection-configmap
#                key: db-connection-string

      restartPolicy: Always
      terminationGracePeriodSeconds: 45 
---
kind: Service
apiVersion: v1
metadata:
  labels: #PODS
    app: aks01-web
  name: aks01-web
  namespace: aks01-web
  
spec:
  selector:
    app: aks01-web
  sessionAffinity: None 
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    # nodePort: 5500 
  type: LoadBalancer
