apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks01-web
  namespace: default
  labels:
    app: aks01-web
spec:
  selector:
    matchLabels:
      app: aks01-web
  replicas: 1 # run in 2 Pods
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aks01-web        
    spec:
      containers:
      - name: mvc
        image: gbbuenaflor/web01aks:256 # #{ImageTag}# #v10 #v2.#{Build.BuildId}#
        imagePullPolicy: Always #IfNotPresent
        ports:
        - name: container-port
          containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "100m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: container-port
          failureThreshold: 15
          periodSeconds: 10
          initialDelaySeconds: 120
        livenessProbe:
          httpGet:
            path: /
            port: container-port
          failureThreshold: 15
          periodSeconds: 10
          initialDelaySeconds: 120
#        env:
#          - name: ConnectionStrings__WebDataContext
#            valueFrom:
##              secretKeyRef:
##                name: mssql-secret
##                key: db-connection-string-secret
#              configMapKeyRef:
#                name: mssql-connection-configmap
#                key: db-connection-string

      restartPolicy: Always
      terminationGracePeriodSeconds: 45 
---
kind: Service
apiVersion: v1
metadata:
  labels: #PODS
    app: aks01-web
  name: aks01-web
  namespace: default
  
spec:
  selector:
    app: aks01-web
  sessionAffinity: None 
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    # nodePort: 5500 
  type: LoadBalancer
